{% set version = "4.12.0" %}

package:
  name: tlsh
  version: {{ version }}

source:
  url: https://github.com/trendmicro/tlsh/archive/{{ version }}.tar.gz
  sha256: 93d206e999d51b25bc800f01c1a88dd632849b1555ca8680264486738f39f3c2
  patches:
    - 0000-cmake-flags.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - ninja
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - test -f ${CONDA_PREFIX}/lib/libtlsh.${SHLIB_EXT}

outputs:
  - name: libtlsh
    script: install-libtlsh.sh
    build:
      run_exports:
        - {{ pin_subpackage('libtlsh', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
    test:
      commands:
        - echo libtlsh tested are during build
  - name: python-tlsh
    script: install-python-tlsh.sh
    build:
      run_exports:
        - {{ pin_subpackage('python-tlsh', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
      host:
        - {{ pin_subpackage('libtlsh', exact=True) }}
        - pip
        - python
        - setuptools
      run:
        - {{ pin_subpackage('libtlsh', exact=True) }}
        - python
    test:
      requires:
        - pip
      imports:
        - tlsh
      commands:
        - pip check
        # - echo "TODO: restore the tests when python_test.sh works"
        # cd Testing && sh python_test.sh
  - name: tlsh-tools
    script: install-tlsh-tools.sh
    build:
      run_exports:
        - {{ pin_subpackage('libtlsh', max_pin='x.x') }}
    test:
      commands:
        - tlsh --help
        - tlsh_unittest --help
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
      host:
        - {{ pin_subpackage('libtlsh', exact=True) }}
      run:
        - {{ pin_subpackage('libtlsh', exact=True) }}

about:
  home: https://github.com/trendmicro/tlsh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TLSH is a fuzzy matching library.
  description: |
    Given a byte stream with a minimum length of 50 bytes TLSH generates a
    hash value which can be used for similarity comparisons. Similar objects
    will have similar hash values which allows for the detection of similar
    objects by comparing their hash values. Note that the byte stream should
    have a sufficient amount of complexity. For example, a byte stream of
    identical bytes will not generate a hash value.

extra:
  recipe-maintainers:
    - bollwyvl
