schema_version: 1

context:
  version: "5.0.0"

recipe:
  name: tlsh
  version: ${{ version }}

source:
  - target_directory: src
    url: https://github.com/trendmicro/tlsh/archive/${{ version }}.tar.gz
    sha256: 2e513993b6b08380dd03777c22caab33a6d0d93ef230250b1b12027d9b7d8a4b
    patches:
      - 0000-fix-cmake-flags.txt
  - target_directory: py
    url: https://pypi.org/packages/source/p/py-tlsh/py_tlsh-${{ version }}.tar.gz
    sha256: a21cb75eb49e9d9237c8c39d2fb310a5c976b3abc6c35c2e405e16c089abad1b

build:
  number: 0
  skip: win

outputs:
  - staging:
      name: staging
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake <4
        - ninja
    build:
      script:
        file: build-staging

  - inherit: staging
    package:
      name: libtlsh
    build:
      script:
        file: build-output.sh
    requirements:
      build:
        - ${{ stdlib('c') }}
      run_exports:
        - ${{ pin_subpackage('libtlsh', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - tlsh/*.h
          lib:
            - libtlsh
            - libtlsh.a
            - libtlsh.so
            - libtlsh.so.${{ (version | split("."))[0] }}
            - libtlsh.so.${{ version }}
          strict: true

  - inherit: staging
    package:
      name: tlsh-tools
    build:
      script:
        file: build-output.sh
    requirements:
      build:
        - ${{ stdlib('c') }}
      host:
        - ${{ pin_subpackage('libtlsh', exact=True) }}
      run:
        - ${{ pin_subpackage('libtlsh', exact=True) }}
    tests:
      - package_contents:
          bin:
            - tlsh
            - tlsh_unittest
          strict: true
      - script:
          - tlsh -help
          - tlsh_unittest -help

  - package:
      name: python-tlsh
    build:
      script:
        file: build-output.sh
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake <4
        - ninja
      host:
        - pip
        - python
        - setuptools
      run:
        - python
      run_constraints:
        - ${{ pin_subpackage('libtlsh', exact=True) }}
    tests:
      - python:
          imports: tlsh
          pip_check: true
      - requirements:
          run:
            - tlsh-tools
            - pytest
        script:
          file: run_test.py
    about:
      homepage: https://pypi.org/project/py-tlsh

about:
  license: Apache-2.0 OR BSD-3-Clause
  license_file:
    - src/LICENSE
    - src/NOTICE.txt
  summary: TLSH is a fuzzy matching library.
  homepage: https://github.com/trendmicro/tlsh
  repository: https://github.com/trendmicro/tlsh
  description: |-
    Given a byte stream with a minimum length of 50 bytes TLSH generates a
    hash value which can be used for similarity comparisons. Similar objects
    will have similar hash values which allows for the detection of similar
    objects by comparing their hash values. Note that the byte stream should
    have a sufficient amount of complexity. For example, a byte stream of
    identical bytes will not generate a hash value.

extra:
  recipe-maintainers:
    - bollwyvl
