travis:
  secure:
    BINSTAR_TOKEN: nQRxxOmaRC0uHM8vyPzps+yJks+6MQyfUrWdae0niZegSU3EsxYtDXB6PfmMD5zCJsPiqLMBltVFGsoPJMX3CdEyY1UHGo0pn2kpFrHz03FAIGaEt0jlqv6DbO4qtHWVSfZmmMzM4VgcgroagLSHDTJ2eEAc5RgHbXV1CvrO7P1ruYv6FeXxBFoAjbHxmDikwe9llaPQ7wwPYTtq1bU0dYbR5OisiQ5fy6qeEsUv2VheNQuRGxmZD47GJxCMbudmcqsFKeg6Eguml0JJl86b/m1hdadJ95bBwIgj058dLUyeXxNCUJnKRoKmZsTZfoLgEKAzLKOGVdigL23OCVFq9LP8fHN8vHouuawZbIknOcxfULy1CFSEkh64t25C0phDbrmasHF+8gbXNZBOd1Wph7MwOGjjO3TZMv44S3m/LoywKb0DxsSbBuN3wFxh9LYNs3+UjLy5q75efuqPKaNbQ57/60b1mWnodLKzneKCKTgShG6Wws5ii9kfszcfxiP4sDcR6zQIsE0kL6zsfrMME7XKCogvRpVHWOCOWjYJju0TOrouWbfK1mBUypve5h3LecJdRQgvjcWkC19XeIlwUW8XQ9E2+/h/d+0PqsWWhosW+oXVTYod/MHUFV9ICS83GFM53G60Wcge82lhQsv3cSTmyiOlaBkOsKWUlujIJnE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
